// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE6Eo38GO9U3d-vWC_s2v_MBwHHnqV7IE',
    appId: '1:329082582863:web:aba9cbef266bb29712373a',
    messagingSenderId: '329082582863',
    projectId: 'alljob-4116a',
    authDomain: 'alljob-4116a.firebaseapp.com',
    storageBucket: 'alljob-4116a.appspot.com',
    measurementId: 'G-J2HJ82169X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ5ZHWB-K5oazirf_xBmCwk2yRQYwx2p8',
    appId: '1:329082582863:android:4a0290269204f2bd12373a',
    messagingSenderId: '329082582863',
    projectId: 'alljob-4116a',
    storageBucket: 'alljob-4116a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxlnn_GS1PseYQXOsHn2HRFahQ4iVzduI',
    appId: '1:329082582863:ios:c19516970220276712373a',
    messagingSenderId: '329082582863',
    projectId: 'alljob-4116a',
    storageBucket: 'alljob-4116a.appspot.com',
    iosClientId: '329082582863-c0jap0d1sdidshd01fes779r0up75ss4.apps.googleusercontent.com',
    iosBundleId: 'regisappvhome.allJob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxlnn_GS1PseYQXOsHn2HRFahQ4iVzduI',
    appId: '1:329082582863:ios:13ef9e1315ff30ee12373a',
    messagingSenderId: '329082582863',
    projectId: 'alljob-4116a',
    storageBucket: 'alljob-4116a.appspot.com',
    iosClientId: '329082582863-g5fbtp1mu7t0v1a08k16flqkmh49pkak.apps.googleusercontent.com',
    iosBundleId: 'com.example.allJob',
  );
}
